# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty


# Setup
title:            WCHENG
tagline:          'Warren Cheng'
description:      'Trying to write regularly...'
# url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Warren Cheng'
#   url:            

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/jn8029/jn8029.github.io
