# Dependencies
highlighter:      rouge

# Permalinks
permalink:        prettys


# Setup
title:            W9G
tagline:          'Warren Cheng'
description:      'Trying to write regularly about tech and finance...or I might just ramble.'
# url:              http://hyde.getpoole.com
baseurl:          https://warrencheng.dev/

author:
  name:           'Warren Cheng'
#   url:

paginate:         5

# Custom vars
version:          2.1.0

github:           https://github.com/jn8029/
