# Dependencies
highlighter:      rouge

# Permalinks
permalink:        prettys


# Setup
title:            W9G
tagline:          'Warren Cheng'
description:      'Feel free to connect with me through <a href="https://www.linkedin.com/in/warrenycheng/">LinkedIn</a>; Or just shoot me an <a href="mailto: warren.y.cheng@gmail.com">Email</a>.'
# url:              http://hyde.getpoole.com
baseurl:          https://warrencheng.dev/

author:
  name:           'Warren Cheng'
#   url:

paginate:         5

# Custom vars
version:          2.1.0

github:           https://github.com/jn8029/
