# Dependencies
highlighter: rouge

# Permalinks
permalink: /:title/

google_analytics: UA-97874793-2
# Setup
title: W9G
tagline: "Warren Cheng"
description: 'Feel free to shoot me an <a href="mailto:">Email</a> if you have any question.'
# url:              http://hyde.getpoole.com
baseurl:

author:
  name: "Warren Cheng"
#   url:

paginate: 10

# Custom vars
version: 2.1.0

github: https://github.com/dittolooch/
plugins:
  - jemoji
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-gist
